name: Update Search Index
on:
  push:
    branches:
      - main
jobs:
  updateIndex:
    runs-on: ubuntu-latest
    steps:
      - env:
          SECRET_ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: Change dir to doc
      - name: Setup gems and jekyll
        working-directory: ./docs
        run: |
            gem install jekyll bundler
            bundle install
            bundle update
      - name: Update Algolia Index
        working-directory: ./docs
        run: |
          ALGOLIA_API_KEY="$SECRET_ALGOLIA_API_KEY" bundle exec jekyll algolia