on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      baseurl: "/sirius-docs.github.io"
      url: ${{ steps.deployment.outputs.page_url }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Staging
        id: deployment
        uses: actions/deploy-pages@v4