# .github/workflows/deploy-main.yaml
name: Build and Deploy Main Branch

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  # This job gets the environment URL and triggers the build
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # This job is now triggered by the deploy job
  build:
    needs: deploy
    uses: ./.github/workflows/reusable-build.yaml
    with:
      # Pass the final deployment URL to the build
      url: ${{ needs.deploy.outputs.page_url }}