name: Update Search Index
on:
  push:
    branches:
      - main
jobs:
  updateIndex:
    runs-on: ubuntu-latest
    # The working-directory can be set for the entire job to avoid repeating it in each step.
    # This also solved ruby gems security issue popping up when installed in insecure location
    defaults:
      run:
        working-directory: ./docs
    env:
      SECRET_ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Update Algolia Index
        run: |
          ALGOLIA_API_KEY="$SECRET_ALGOLIA_API_KEY" bundle exec jekyll algolia